"""Public operators, kernel adapters, backend registry, and runtime policy.

``backend`` selects implementations, ``kernel`` calls exact compiled modules,
``dispatch`` controls priority and train/infer capability, and ``plan`` owns
the GEMM configuration facade.
"""

from astrai.extension.backend import (
    ATTN_BACKEND,
    AttentionBackend,
    AttentionBackendFactory,
    CudaBackend,
    FlashAttnBackend,
    TorchNativeBackend,
    apply_rotary_emb,
    attention,
    attn_backend,
    get_backend,
    newton_schulz,
    symm_out,
    syrk_out,
)
from astrai.extension.kernel import (
    TensorLayout,
    attn_decode,
    attn_paged_decode,
    attn_paged_prefill,
    attn_prefill,
    cross_entropy,
    linear_cross_entropy,
)
from astrai.extension.kernel.gemm import (
    facts,
    probe,
    set_log,
    set_planner,
    set_staging,
    set_table,
    state,
    tile_vocabulary,
)
from astrai.extension.kernel.quantize import (
    quantize_act_int8,
    quantize_weight_int8,
)
from astrai.extension.policy.gemm import autotune, plan
from astrai.extension.policy.gemm.plan import PLANNER_MODES
from astrai.extension.policy.quantization import autocast, fp8_slots
from astrai.extension.policy.quantization.autocast import (
    FP8Recipe,
    fp8_autocast,
    fp8_format_pair,
    fp8_linear_enable,
    fp8_linear_enabled,
    fp8_load_state_dict,
    fp8_reset,
    fp8_state_dict,
)
from astrai.extension.runtime import dispatch, loader
from astrai.extension.runtime.dispatch import (
    Axes,
    ExplicitSelectionError,
    ImplRecord,
    Resolution,
    Spec,
    axis,
    explain,
    explain_plan,
    op_backend,
    register_env_alias,
    register_family,
    register_impl,
    resolve,
    resolve_plan,
    set_op,
    tensor_axes,
    unregister_impl,
)
from astrai.extension.runtime.loader import KERNEL_NAMES, is_available

__all__ = [
    "cross_entropy",
    "linear_cross_entropy",
    "ATTN_BACKEND",
    "AttentionBackend",
    "AttentionBackendFactory",
    "CudaBackend",
    "TorchNativeBackend",
    "FlashAttnBackend",
    "TensorLayout",
    "attention",
    "attn_backend",
    "get_backend",
    "attn_decode",
    "attn_paged_decode",
    "attn_prefill",
    "attn_paged_prefill",
    "is_available",
    "KERNEL_NAMES",
    "apply_rotary_emb",
    "newton_schulz",
    "symm_out",
    "syrk_out",
    "FP8Recipe",
    "fp8_autocast",
    "fp8_format_pair",
    "fp8_linear_enable",
    "fp8_linear_enabled",
    "fp8_load_state_dict",
    "fp8_reset",
    "fp8_state_dict",
    "quantize_act_int8",
    "quantize_weight_int8",
    "Axes",
    "ExplicitSelectionError",
    "ImplRecord",
    "Resolution",
    "Spec",
    "axis",
    "set_op",
    "explain",
    "explain_plan",
    "op_backend",
    "register_env_alias",
    "register_family",
    "register_impl",
    "resolve",
    "resolve_plan",
    "tensor_axes",
    "unregister_impl",
    "PLANNER_MODES",
    "plan",
    "facts",
    "probe",
    "set_log",
    "set_planner",
    "set_staging",
    "set_table",
    "state",
    "tile_vocabulary",
]
